api_platform:
    mapping:
        paths: ['%kernel.project_dir%/applicationSymfony/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
