knp_dictionary:
    dictionaries:

        product_type:
            type: 'key_value'
            content:
                "book": "Book"
                "magabook": "Magabook"
                "booklet": "Booklet"
                "tract": "Tract"
        product_sort:
            type: 'key_value'
            content:
                "name": "Title"
                "author": "Author"
                "publisher": "Publisher"
        file_type:
            type: 'key_value'
            content:
                "pdf_printing": "PDF (Production)"
                "pdf_personal": "PDF (Personal)"
                "indd": "InDesign"
            
