knp_dictionary:
    dictionaries:
        product_type:
            type: 'key_value'
            content:
                "book": "product.field.type.values.book"
                "magabook": "product.field.type.values.magabook"
                "booklet": "product.field.type.values.booklet"
                "tract": "product.field.type.values.tract"
        product_sort:
            type: 'key_value'
            content:
                "name": "product.sort.name"
                "author": "product.sort.author"
                "publisher": "product.sort.publisher"
        file_type:
            type: 'key_value'
            content:
                "pdf_printing": "attachment.field.type.values.pdf_prod"
                "pdf_personal": "attachment.field.type.values.pdf_perso"
                "indd": "attachment.field.type.values.indesign"
        content_revision_status:
            type: 'key_value'
            content:
                !php/const App\Entity\ContentRevision::STATUS_TRANSLATED: "content_revision.status.new"
                !php/const App\Entity\ContentRevision::STATUS_PROOFREAD: "content_revision.status.proofread"
                !php/const App\Entity\ContentRevision::STATUS_REVIEWED: "content_revision.status.reviewed"
