framework:
  workflows:
    project:
      type: 'state_machine'
      marking_store:
        type: 'method'
        property: 'status'
      supports:
        - App\Entity\Project
      initial_marking: !php/const App\Entity\Project::STATUS_TRANSLATABLE
      places:
        - !php/const App\Entity\Project::STATUS_TRANSLATABLE
        - !php/const App\Entity\Project::STATUS_STARTED
        - !php/const App\Entity\Project::STATUS_TRANSLATED
        - !php/const App\Entity\Project::STATUS_APPROVED
        - !php/const App\Entity\Project::STATUS_REVIEWED
        - !php/const App\Entity\Project::STATUS_DOWNLOADABLE
      transitions:
        !php/const App\Entity\Project::TRANSITION_START:
          from: !php/const App\Entity\Project::STATUS_TRANSLATABLE
          to: !php/const App\Entity\Project::STATUS_STARTED
        !php/const App\Entity\Project::TRANSITION_DECLARE_TRANSLATED:
          from: !php/const App\Entity\Project::STATUS_STARTED
          to: !php/const App\Entity\Project::STATUS_TRANSLATED
        !php/const App\Entity\Project::TRANSITION_DECLARE_APPROVED:
          from: !php/const App\Entity\Project::STATUS_TRANSLATED
          to: !php/const App\Entity\Project::STATUS_APPROVED
        !php/const App\Entity\Project::TRANSITION_DECLARE_REVIEWED:
          from: !php/const App\Entity\Project::STATUS_APPROVED
          to: !php/const App\Entity\Project::STATUS_REVIEWED
        !php/const App\Entity\Project::TRANSITION_UPLOAD_RESULT:
          from: !php/const App\Entity\Project::STATUS_REVIEWED
          to: !php/const App\Entity\Project::STATUS_DOWNLOADABLE
