version: '3.4'

services:
  ac-db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somePassword
    command: --init-file /data/application/init.sql
    volumes:
        - ./docker/mysql/init.sql:/data/application/init.sql

  ac-webserver:
    image: phpdockerio/nginx:latest
    container_name: ac-webserver
    volumes:
      - .:/var/www/adventistcommons:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx:/var/log/nginx
    ports:
      - "8096:80"
    links:
      - ac-php-fpm
    expose:
      - 8096

  ac-php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: ac-php-fpm
    ports:
      - 9000:9000
    volumes:
      # read only
      - .:/var/www/adventistcommons:ro
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini:ro
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini:ro
      # read/write
      - ./public/bundles:/var/www/adventistcommons/public/bundles
      - ./var:/var/www/adventistcommons/var
      - ./uploads:/var/www/adventistcommons/uploads
      - ./src/Migrations:/var/www/adventistcommons/src/Migrations
    working_dir: /var/www/adventistcommons
    links:
      - ac-db
      - ac-nltk
    depends_on:
      - ac-db

  ac-adminer:
    image: adminer:latest
    container_name: ac-admniner
    links:
      - ac-db
    ports:
      - 8080:8080

  ac-composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - .:/app
      - ./var/cache/composer:/tmp

  ac-admin:
    build:
      context: ./admin
      target: api_platform_admin_development
      cache_from:
        - ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    image: ${ADMIN_IMAGE:-quay.io/api-platform/admin}
    volumes:
      - ./admin:/usr/src/admin:rw,cached
    ports:
      - target: 3000
        published: 8097
        protocol: tcp
        
  ac-node:
    image: "node:8"
    user: node
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    expose:
      - "8081"
    command: "npm start"

  ac-nltk:
    build:
      context: ./docker/nltk
    command: "python3 -m nlp_api ac-nltk 2230"

# FOR DNS problems, see here : https://development.robinwinslow.uk/2016/06/23/fix-docker-networking-dns/
