app_auth:
    resource: App\Controller\AuthController
    type: annotation
    prefix: /{_locale}/auth

app_auth_social:
    resource: App\Controller\AuthSocialController
    type: annotation
    prefix: /{_locale}/auth/social

app_dashboard:
    resource: App\Controller\DashboardController
    type: annotation
    prefix: /{_locale}/dashboard

app_account:
    resource: App\Controller\AccountController
    type: annotation
    prefix: /{_locale}/account

app_about:
    resource: App\Controller\AboutController
    type: annotation
    prefix: /

app_product:
    resource: App\Controller\ProductController
    type: annotation
    prefix: /{_locale}/products

app_idml:
    resource: App\Controller\IdmlController
    type: annotation
    prefix: /{_locale}/idml

app_products:
    resource: App\Controller\ProductsController
    type: annotation
    prefix: /{_locale}/product

app_project:
    resource: App\Controller\ProjectController
    type: annotation
    prefix: /{_locale}/products

app_attachment:
    resource: App\Controller\AttachmentController
    type: annotation
    prefix: /{_locale}/products

app_projects:
    resource: App\Controller\ProjectsController
    type: annotation
    prefix: /{_locale}/projects

app_section:
    resource: App\Controller\SectionController
    type: annotation
    prefix: /{_locale}/products

app_feedback:
    resource: App\Controller\FeedbackController
    type: annotation
    prefix: /{_locale}/feedback

app_auth_login_check:
    path:     /account/login_check
    methods:  [POST]

app_auth_login_check_json:
    path:     /api/login_check
    methods:  [POST]

app_auth_logout:
    path:     /account/logout
