
---
-
  name: Deploy Application
  hosts: all
  gather_facts: false
  vars:
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: "{{ deploy_to }}"
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: "{{ repository }}"
    ansistrano_git_branch: "{{ git_reference }}"
    ansistrano_shared_paths:
      - var
      - uploads
    ansistrano_shared_files:
      - .env.local
    symfony_console_path: 'bin/console'
    symfony_run_assetic_dump: false
    symfony_run_doctrine_migrations: true
    ansistrano_after_update_code_tasks_file: "{{ playbook_dir }}/tasks/npm.yml"
  roles:
    - { role: cbrunnkvist.ansistrano-symfony-deploy }
  environment:
    APP_ENV: "{{ sf_env }}"
    BASE_URL: "{{ sf_base_url }}"
    HOST: "{{ sf_host }}"
    SCHEME: "{{ sf_scheme }}"
  
# npm install
# npm run build