# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    coverTargetDirectory: '%kernel.project_dir%/uploads/covers'
    coverReadPath: '/uploads/covers/'
    idmlTargetDirectory: '%kernel.project_dir%/uploads/idmls'
    attachmentTargetDirectory: '%kernel.project_dir%/uploads/attachments'
    pdfTargetDirectory: '%kernel.project_dir%/uploads/pdfs'
    nlpHost: '%env(string:NLP_HOST)%'
        
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        
    AdventistCommons\:
        resource: '../domain/*'
        exclude: '../domain/Idml/{Entity,DomManipulation}'

    App\Security\UserPasswordUpdater:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Product\EventSubscriber\SlugSetter:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Product\Uploader\CoverUploader:
        arguments: 
            - '%coverTargetDirectory%'        

    App\Product\Uploader\PdfDigitalUploader:
        arguments: 
            - '%pdfTargetDirectory%'        

    App\Product\Uploader\PdfOffsetUploader:
        arguments: 
            - '%pdfTargetDirectory%'       

    App\Product\Uploader\IdmlUploader:
        arguments: 
            - '%idmlTargetDirectory%'        

    App\Product\Uploader\AttachmentUploader:
        arguments: 
            - '%attachmentTargetDirectory%'        

    Symfony\Component\Form\ChoiceList\Factory\ChoiceListFactoryInterface:
        alias: form.choice_list_factory.default
        
    AdventistCommons\Idml\HolderBuilder:
        arguments:
            - '@AdventistCommons\Idml\DomManipulation\StoryBasedOnTags'
            
    AdventistCommons\Idml\DomManipulation\StoryBasedOnTags: ~

    App\Response\JsonResponseBuilder: ~

    App\Nlp\Client:
        arguments:
            - '%nlpHost%'
